name: devenv
description: devenv is a simple development tool that makes developing software easy across multiple languages
version: 0.1.0

executables: 
  devenv:

environment:
  sdk: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.15
  cli_pkg: ^2.12.0
  grinder: ^0.9.5
  json_serializable: ^6.9.5
dependencies:
  args: ^2.7.0
  glob: ^2.1.3
  io: ^1.0.5
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path: ^1.9.1
  yaml: ^3.1.3
